services:
  mysql:
    image: mysql:8.0
    container_name: ticket_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: it_support_ticket_system
      MYSQL_USER: user
      MYSQL_PASSWORD: pass123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    container_name: ticket_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://user:pass123@mysql:3306/it_support_ticket_system"
    command: >
      sh -c "
        echo 'â³ Waiting for MySQL...';
        until nc -z mysql 3306; do
          echo '   â†’ MySQL not ready, retrying...';
          sleep 2;
        done;
        echo 'ğŸŸ¢ Running Prisma db push...';
        npx prisma db push;
        echo 'ğŸš€ Starting backend...';
        npm start
      "

volumes:
  mysql_data:
